name: Laravel Deployer Workflow

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
          check-latest: true

      - name: Install NPM dependencies
        run: npm install

      - name: Compile assets for production
        run: npm run production

      - name: Commit built assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout production
          git add public
          git commit -m "Build front-end assets"
          git push origin production

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/test.crud/
            php artisan down || true
            git checkout production
            git pull
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan cache:clear
            php artisan auth:clear-resets
            php artisan route:cache
            php artisan config:cache
            php artisan view:cache
            php artisan queue:restart
            php artisan up
            composer dump-autoload
